
package edu.uci.fallsensor.service;

public enum BLEState {
    CHARACTERISTIC_NOTIFICATION_WRITE,
    CHARACTERISTIC_WRITE,
    CHARACTERISTIC_CHANGED,
    CHARACTERISTIC_READ,
    DESCRIPTOR_WRITE,
    DESCRIPTOR_READ,
    DEVICE_CONNECT,
    DEVICE_SERVICE,
    DEVICE_DISCONNECT;
}
